Adding methods mtcaptcha, friendly captcha, cutcaptcha
2captcha/2captcha-python pull request #73
Opened 2024-03-25 09:46 UTC by poplers24

## Done

- Adding methods `mtcaptcha`, `friendly captcha`, `cutcaptcha` to `solver.py`
- Adding examples `mtchaptcha.py`, `mtcaptcha_options.py`, `friendly_captcha.py`, `friendly_captcha_options.py`, `cutcaptcha.py`, `cutcaptcha_options.py` to examples folder
- Adding tests `test_mtcaptcha.py`, `test_friendly_captcha.py`, `test_cutcaptcha.py` to tests folder

2024-03-30 03:24 UTC, kratzky commented on tests/test_cutcaptcha.py
> +            'method':     'cutcaptchaа',
Опечатка, лишняя `a`

2024-03-30 03:24 UTC, kratzky requested changes
Нужно исправить опечатку, из-за нее валится тест.

2024-04-01 09:10 UTC, poplers24 commented on tests/test_cutcaptcha.py
> +            'method':     'cutcaptchaа',
## Done

- Fixed parameter `{'method': 'cutcaptcha'}` in the `send` parameters of the send request in the file `test_cutcaptcha.py`
- Adding `.idea/`, `.DS_Store` to `.gitignore`

2024-04-01 09:11 UTC, poplers24 commented
@kratzky исправил

2024-04-01 10:44 UTC, merged